Feature - Add endpoint to get all tasks
rajeshsinha1997/task-manager-rest-java pull request #4
Opened 2024-03-03 12:32 UTC by AlexeyShary

PR for issue https://github.com/rajeshsinha1997/task-manager-rest-java/issues/2

- Implemented doGet method in tmr/src/main/java/controllers/TaskServlet.java
- Implemented getAllTasks method in tmr/src/main/java/services/TaskService.java
- Added and implemented findAllTasks method in tmr/src/main/java/repositories/ITaskRepository.java and tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java

2024-03-03 14:36 UTC, rajeshsinha1997 requested changes
Hi @AlexeyShary, I've requested a few changes, please have a look at them whenever possible for you and make those changes.

2024-03-03 14:36 UTC, rajeshsinha1997 commented on tmr/src/main/java/controllers/TaskServlet.java
> +    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
Rather than throwing the **IOException**, handle it in the catch block.

2024-03-03 14:36 UTC, rajeshsinha1997 commented on tmr/src/main/java/controllers/TaskServlet.java
> +            String jsonResponse = gson.toJson(tasks);
Line No. 39-44:

The same logic of converting an object to JSON and attaching to the response is already present in the CommonServletUtility.java file along with the code block responsible for creating a formatted response. Please reuse that same method here rather than re-writing the same code.

2024-03-03 14:36 UTC, rajeshsinha1997 commented on tmr/src/main/java/controllers/TaskServlet.java
> +            CommonServletUtility.buildErrorResponse(resp, 500, e);
Add a logic to send the response code accordingly depending on the exception. Refer to the ***catch*** block of the **POST** method implementation.

2024-03-03 14:36 UTC, rajeshsinha1997 commented on tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
> +        return new ArrayList<>(tasks.values());
Rather than type-casting to a specific object type, I'll suggest to type-cast to the interface type as below,

(List<TaskModel>) this.tasks.values()

2024-03-03 14:36 UTC, rajeshsinha1997 commented on tmr/src/main/java/services/TaskService.java
> +    /**
Generate a proper Javadoc comment string

2024-03-03 14:36 UTC, rajeshsinha1997 commented on tmr/src/main/java/services/TaskService.java
> +        List<TaskModel> allTasks = taskRepository.findAllTasks();
You can directly return the value after receiving it from the repository, no need to run a stream to collect them into a separate list.

2024-03-03 15:34 UTC, AlexeyShary commented on tmr/src/main/java/controllers/TaskServlet.java
> +    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
Done - now without gson there can't be IOException

2024-03-03 15:34 UTC, AlexeyShary commented on tmr/src/main/java/controllers/TaskServlet.java
> +            String jsonResponse = gson.toJson(tasks);
Done

2024-03-03 15:34 UTC, AlexeyShary commented on tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
> +        return new ArrayList<>(tasks.values());
Done

2024-03-03 15:34 UTC, AlexeyShary commented on tmr/src/main/java/services/TaskService.java
> +    /**
Done

2024-03-03 15:36 UTC, AlexeyShary commented on tmr/src/main/java/services/TaskService.java
> +        List<TaskModel> allTasks = taskRepository.findAllTasks();
Didn't quite understand. The repository returns a List<TaskModel>, and then we're collecting it into a List<TaskDataResponseDTO> using a stream.

2024-03-04 03:26 UTC, rajeshsinha1997 commented on tmr/src/main/java/services/TaskService.java
> +        List<TaskModel> allTasks = taskRepository.findAllTasks();
Sorry, my bad! I overlooked the part where we need to map the fetched Task data from the repository to the DTO object

2024-03-04 03:26 UTC, rajeshsinha1997 approved these changes
LGTM

2024-03-04 03:27 UTC, merged